import { Geist, Geist_Mono, Roboto_Condensed } from "next/font/google";
import "./globals.css";
import Header from "@/ui/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const robotoCondensed = Roboto_Condensed({
  variable: "--font-roboto-condensed",
  subsets: ["latin"],
})

export const metadata = {
  title: "Suitmedia Intern",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
      <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'/>
    </head>
    <body className={`${geistSans.variable} ${geistMono.variable} ${robotoCondensed.variable}`}>
        <Header/>
        {children}
    </body>
    </html>
  );
}
